KTB-14 парсинг update_id с использованием Regex
PavelMordukhai/KotlinTelegramBot pull request #11
Opened 2024-09-16 15:00 UTC by PavelMordukhai

2024-09-17 05:49 UTC, kaznikit requested changes

2024-09-17 05:49 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +        updateId = updateId?.plus(1)
все супер, но зачем мы 2 раза записываем updateId? может оставить только 1 раз?)

2024-09-17 07:22 UTC, PavelMordukhai commented on src/main/kotlin/Telegram.kt
> +        updateId = updateId?.plus(1)
ок

2024-09-18 13:54 UTC, kaznikit approved these changes

2024-09-18 15:12 UTC, merged