KTB-22 многопользовательский режим + сброс статистики
PavelMordukhai/KotlinTelegramBot pull request #18
Opened 2024-10-01 18:26 UTC by PavelMordukhai

2024-10-02 15:15 UTC, kaznikit requested changes

2024-10-02 15:15 UTC, kaznikit commented on src/main/kotlin/LearnWordsTrainer.kt
> +                File("words.txt").copyTo(wordsFile)
у нас есть fileName, нужно использовать его)

2024-10-02 15:15 UTC, kaznikit commented on src/main/kotlin/Telegram.kt
> +            else -> "\nНеправильно! ${trainer.getQuestion()?.correctAnswer?.original} " +
может выводить информацию также внутри функции checkAnswer, чтобы не делать дополнительную функцию getQuestion?

2024-10-02 15:35 UTC, PavelMordukhai commented on src/main/kotlin/LearnWordsTrainer.kt
> +                File("words.txt").copyTo(wordsFile)
точно

2024-10-02 17:39 UTC, PavelMordukhai commented on src/main/kotlin/Telegram.kt
> +            else -> "\nНеправильно! ${trainer.getQuestion()?.correctAnswer?.original} " +
ок

2024-10-02 17:44 UTC, PavelMordukhai commented on src/main/kotlin/Telegram.kt
> +            else -> "\nНеправильно! ${trainer.getQuestion()?.correctAnswer?.original} " +
Но чтобы не обращаться к TelegramBotService.sendMessage из LearnWordsTrainer.checkAnswer, я решил вернуть строку из функции сюда же, чтобы не было конфликтов с Main.kt

2024-10-03 09:13 UTC, kaznikit approved these changes

2024-10-03 09:16 UTC, merged