KTB-07 функционал изучения слов: варианты ответа
PavelMordukhai/KotlinTelegramBot pull request #5
Opened 2024-09-03 14:01 UTC by PavelMordukhai

2024-09-04 09:29 UTC, kaznikit requested changes

2024-09-04 09:29 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                    for (i in answers.indices) {
давай использовать функцию `forEachIndexed`, либо попробовать сделать с помощью функции `joinToString`, чтобы оставить только 1 вывод

2024-09-04 09:29 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                    else {
похоже что else можно удалить

2024-09-04 09:29 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +    val wordsFile = File("words.txt")
давай создадим файл и будем просто его считывать. чтобы не нужно было каждый раз пересоздавать его

2024-09-04 09:29 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                    val answers = if (unlearnedWordsCount <= NUMBER_OF_ANSWER_CHOICES)
вроде `take` внутри обрабатывает такую ситуацию. попробуй убрать этот if

2024-09-04 09:42 UTC, PavelMordukhai commented on src/main/kotlin/Main.kt
> +                    val answers = if (unlearnedWordsCount <= NUMBER_OF_ANSWER_CHOICES)
точно

2024-09-04 10:21 UTC, PavelMordukhai commented on src/main/kotlin/Main.kt
> +                    for (i in answers.indices) {
а вот тут пришлось подумать

2024-09-05 05:27 UTC, kaznikit approved these changes

2024-09-05 05:35 UTC, merged