KTB-10 исправления багов
PavelMordukhai/KotlinTelegramBot pull request #8
Opened 2024-09-10 11:25 UTC by PavelMordukhai

2024-09-10 11:33 UTC, PavelMordukhai commented
Баги, которых не было в видео:

- исправил вывод английского слова, когда невыученных оставалось меньше чем количество вариантов: теперь в этом случае не отображается выученное английское слово;

- исправил ввод ответа пользователем: при неверном слове возникает предупреждение и запрос на повторный ввод, при этом слово не меняется на следующее, пока ввод некорректен.

Возможно реализовано коряво )

2024-09-11 09:08 UTC, kaznikit requested changes

2024-09-11 09:08 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                    do {
не нравится как выглядит этот цикл, можно его немного оптимизировать. например в цикле считывать ввод пользователя только если введенное число не попадает в диапазон:
```
do {
   print("Введите номер ответа либо 0: ")
   userAnswerInput = readln().trim().toIntOrNull()
} while (userAnswerInput !in 0..NUMBER_OF_ANSWER_CHOICES)
```
а дальше применить when, вместо if. должно выглядеть получше)

2024-09-11 09:08 UTC, kaznikit commented on src/main/kotlin/LearnWordsTrainer.kt
> +            correctAnswer = answerOptions.random()
можем вынести за if и получать таким образом:
`val correctAnswer = answerOptions.random()`

2024-09-11 09:18 UTC, PavelMordukhai commented on src/main/kotlin/LearnWordsTrainer.kt
> +            correctAnswer = answerOptions.random()
Тут в том то и дело, что correctAnswer выбирается по-разному. В первом случае выбирается среди оставшихся 1-3 штук невыученных слов, а затем варианты ответов разбавляются выученными словами. Сделано для того, чтобы для 1-3-х оставшихся невыученных слов не создавался вопрос с рандомным выученным словом.

2024-09-11 09:29 UTC, PavelMordukhai commented on src/main/kotlin/LearnWordsTrainer.kt
> +            correctAnswer = answerOptions.random()
В принципе это соответствует требованию "Выводим сообщение с невыученным английским словом" )

2024-09-11 09:45 UTC, PavelMordukhai commented on src/main/kotlin/Main.kt
> +                    do {
Действительно, благодарю )

2024-09-12 08:48 UTC, kaznikit approved these changes

2024-09-12 09:41 UTC, merged